// <auto-generated />
using System;
using DAS901_Desafio2.Data.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAS901_Desafio2.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20220506155347_AgregarClaveForaneaTablaCalificaciones")]
    partial class AgregarClaveForaneaTablaCalificaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAS901_Desafio2.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalificacionPelicula")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPelicula");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("DAS901_Desafio2.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("DAS901_Desafio2.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreGenero = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            NombreGenero = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            NombreGenero = "Comedia"
                        },
                        new
                        {
                            Id = 4,
                            NombreGenero = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            NombreGenero = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            NombreGenero = "Suspenso"
                        },
                        new
                        {
                            Id = 7,
                            NombreGenero = "Fantasía"
                        },
                        new
                        {
                            Id = 8,
                            NombreGenero = "Concierto"
                        },
                        new
                        {
                            Id = 9,
                            NombreGenero = "Documental"
                        });
                });

            modelBuilder.Entity("DAS901_Desafio2.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<bool>("Cartelera")
                        .HasColumnType("bit");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Estreno")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEstreno")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Proximamente")
                        .HasColumnType("bit");

                    b.Property<string>("Reparto")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trailer")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("IdGenero");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Brenda Vanegas",
                            Estreno = false,
                            IdGenero = 4,
                            Nombre = "Antes la lluvia",
                            Proximamente = false,
                            Reparto = "Patricia ,Isabel ,Inma",
                            Sinopsis = "Es la historia de dos mujeres. Maria es una migrante salvadorena que pierde su trabajo tras enfermar y ademas esta terminando una relacion dolorosa. Esther, una mujer mayor que padece alzheimer, esta perdiendo la memoria, y los recuerdos importantes.",
                            Trailer = "https://www.youtube.com/watch?v=w9djCCDhnVI"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "David Moreau",
                            Estreno = false,
                            IdGenero = 2,
                            Nombre = "King Regreso a Casa",
                            Proximamente = false,
                            Reparto = "Gerard ,Lou ,Leo",
                            Sinopsis = "King, un cachorro de leon traficado, escapa del aeropuerto en pleno transito y encuentra refugio en la casa de Ines y Alex, de 12 y 15 anios. A los hermanos se les ocurre un loco plan traer a King de vuelta a Africa.",
                            Trailer = "https://youtu.be/EC7Cm6kSFT4"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Phillip Noyce",
                            Estreno = false,
                            IdGenero = 4,
                            Nombre = "Desesperada",
                            Proximamente = false,
                            Reparto = "Naomi ,Phillip ,Colton ,Sierra",
                            Sinopsis = "Una madre corre desesperadamente contra el tiempo para salvar a su hijo mientras las autoridades cierran su pequenio pueblo.",
                            Trailer = "https://youtu.be/5Ca1mXFv2Fc"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Robert Eggers",
                            Estreno = false,
                            IdGenero = 1,
                            Nombre = "El Hombre del Norte",
                            Proximamente = false,
                            Reparto = "Nicole,Anya ,Akexander",
                            Sinopsis = "El visionario director Robert Eggers presenta EL HOMBRE DEL NORTE, una epica aventura llena de accion que narra la busqueda de un joven principe vikingo por vengar el asesinato de su padre.",
                            Trailer = "https://youtu.be/_fpTJaHOwbw"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Aaron Nee",
                            Estreno = false,
                            IdGenero = 1,
                            Nombre = "La Ciudad Perdida",
                            Proximamente = false,
                            Reparto = "Sandra ,Channing ,Daniel",
                            Sinopsis = "Una novelista romantica solitaria en una gira de libros junto con su modelo de portada se ve envuelta en un intento de secuestro que los lleva a ambos a una feroz aventura en la jungla.",
                            Trailer = "https://youtu.be/Jhl2v32cKzc"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "David Yates",
                            Estreno = false,
                            IdGenero = 2,
                            Nombre = "Animales Fantasticos 3",
                            Proximamente = false,
                            Reparto = "Mads,Jude ,Ezra",
                            Sinopsis = "Albus Dumbledore sabe que el mago oscuro Gellert quiere apoderarse del mundo magico. Como no puede detenerlo solo, le pide al magizoologo Newt Scamander que lidere un grupo de magos, brujas y un valiente panadero muggle hacia una peligrosa mision.",
                            Trailer = "https://youtu.be/QfYgcLuxS5Y"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Jeff Fowler",
                            Estreno = false,
                            IdGenero = 1,
                            Nombre = "Sonic 2 La Pelicula",
                            Proximamente = false,
                            Reparto = "Idris ,Ben ,Colleen",
                            Sinopsis = "Despues de establecerse en Green Hills, Sonic esta listo para tener mas libertad, asi que Tom y Maddie lo dejan solo en casa mientras se van de vacaciones. Pero apenas se han ido, el Dr. Robotnik regresa, esta vez con un nuevo aliado, Knuckles.",
                            Trailer = "https://youtu.be/ahVkLQKoLFw"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = true,
                            Director = "Sam Raimi",
                            Estreno = true,
                            FechaEstreno = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 2,
                            Nombre = "Doctor Strange 2",
                            Proximamente = false,
                            Reparto = "Benedict ,Chiwetel ,Elizabeth",
                            Sinopsis = "Doctor Strange con la ayuda de aliados misticos nuevos y otros ya conocidos por la audiencia, atraviesa las alucinantes y peligrosas realidades alternativas del Multiverso para enfrentarse a un nuevo y misterioso adversario.",
                            Trailer = "https://youtu.be/cFHjZfy50Kk"
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Jason Zada",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 8,
                            Nombre = "Twenty One Pilots Cinema Experience",
                            Proximamente = true,
                            Reparto = "Tyler ,Josh",
                            Sinopsis = "Experimenta la epica celebracion del lanzamiento del album Scaled And Icyde 2021, remasterizado para la gran pantalla y con material inedito.",
                            Trailer = "https://www.youtube.com/watch?v=23gp-Sf1Oo8"
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Andrew Levitas",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 4,
                            Nombre = "El Fotógrafo de Minamata",
                            Proximamente = true,
                            Reparto = "Johnny Depp, Bill Nighy, Hiroyuki Sanada",
                            Sinopsis = "El fotografo de guerra W Eugene Smith viaja a Japon para documentar el envenenamiento por mercurio de comunidades costeras enteras.",
                            Trailer = "https://www.youtube.com/watch?v=QEfGnm_72OQ"
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Martin Campbell",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 1,
                            Nombre = "El Protegido",
                            Proximamente = true,
                            Reparto = "Maggie Q, Michael Keaton, Samuel L. Jackson, Robert Patrick",
                            Sinopsis = "Rescatada de nina por el legendario asesino Moody, Anna es la asesina a sueldo mas habil del mundo. Sin embargo, cuando Moody es brutalmente asesinado, ella jura venganza por el hombre que le enseno todo lo que sabe.",
                            Trailer = "https://youtu.be/SGJ8cOWnqHw"
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Celina Escher",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 9,
                            Nombre = "Nuestra Libertad",
                            Proximamente = true,
                            Reparto = "Teodora Vásquez",
                            Sinopsis = "Despues de cumplir diez anios tras las rejas por su aborto espontaneo, considerado por su gobierno como un acto de homicidio agravado, Teodora Vasquez se convierte en portavoz de las otras 16 mujeres salvadorenas tras las rejas por el mismo delito.",
                            Trailer = "https://www.youtube.com/watch?v=R5keA5nF-TI"
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Martin Campbell",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 1,
                            Nombre = "Asesino sin Memoria",
                            Proximamente = true,
                            Reparto = "Liam Neeson, Guy Pearce, Monica Bellucci, Taj Atwal",
                            Sinopsis = "Alex Lewis es un experto asesino con una reputacion de discreta precision. Cuando Alex se niega a completar un trabajo para una peligrosa organizacion criminal, se convierte en un objetivo y debe ir a la caza de quienes lo quieren muerto.",
                            Trailer = "https://www.youtube.com/watch?v=gUMaCiHNZw0"
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Simon Curtis",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 4,
                            Nombre = "Downton Abbey Una Nueva Era",
                            Proximamente = true,
                            Reparto = "Hugh Bonneville, Michelle Dockery, Imelda Staunton",
                            Sinopsis = "La secuela de la pelicula de 2019 en la que la familia Crawley y el personal de Downton recibieron la visita real del Rey y la Reina de Gran Bretana.",
                            Trailer = "https://www.youtube.com/watch?v=LHZDzAq9yZ8"
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Calificacion = 0,
                            Cartelera = false,
                            Director = "Joseph Kosinski",
                            Estreno = false,
                            FechaEstreno = new DateTime(2022, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdGenero = 1,
                            Nombre = "Top Gun Maverick",
                            Proximamente = true,
                            Reparto = "Tom Cruise, Val Kilmer, Miles Teller, Jennifer Connelly, Glen Powell",
                            Sinopsis = "Despues de mas de 30 anios de servicio como uno de los mejores aviadores de la Armada, Pete Maverick Mitchell esta donde pertenece, forzando los limites como valiente piloto de pruebas y esquivando el avance de rango que lo dejaria en tierra.",
                            Trailer = "https://youtu.be/zzBIzYmxatU"
                        });
                });

            modelBuilder.Entity("DAS901_Desafio2.Models.Calificacion", b =>
                {
                    b.HasOne("DAS901_Desafio2.Models.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAS901_Desafio2.Models.Pelicula", b =>
                {
                    b.HasOne("DAS901_Desafio2.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("IdGenero");
                });
#pragma warning restore 612, 618
        }
    }
}
